sites = {
    "TMUF-X": {
        "url": "tmuf.exchange",
        "tags": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
            "Story",
            "Nascar",
            "SpeedFun",
            "Endurance",
            "Altered Nadeo",
            "Transitional",
        ],
        "primarytypes": ["Race", "Puzzle", "Platform", "Stunts", "Shortcut", "Laps"],
        "environments": [
            "",
            "Snow",
            "Desert",
            "Rally",
            "Island",
            "Coast",
            "Bay",
            "Stadium",
        ],
        "moods": ["Sunrise", "Day", "Sunset", "Night"],
        "inhasrecords": ["No Records", "Has Records"],
        "difficultys": ["Beginner", "Intermediate", "Expert", "Lunatic"],
    },
    "TMNF-X": {
        "url": "tmnf.exchange",
        "tags": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
            "Story",
            "Nascar",
            "SpeedFun",
            "Endurance",
            "Altered Nadeo",
            "Transitional",
        ],
        "primarytypes": ["Race", "Puzzle", "Platform", "Stunts", "Shortcut", "Laps"],
        "environments": ["", "", "", "", "", "", "", "Stadium"],
        "moods": ["Sunrise", "Day", "Sunset", "Night"],
        "inhasrecords": ["No Records", "Has Records"],
        "difficultys": ["Beginner", "Intermediate", "Expert", "Lunatic"],
    },
    "TMO-X": {
        "url": "original.tm-exchange.com",
        "tags": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
        ],
        "primarytypes": ["Race", "Puzzle", "Platform", "Stunts", "Shortcut", "Laps"],
        "environments": ["", "Snow", "Desert", "Rally"],
        "moods": ["Sunrise", "Day", "Sunset", "Night"],
        "inhasrecords": ["No Records", "Has Records"],
        "difficultys": ["Beginner", "Intermediate", "Expert", "Lunatic"],
    },
    "TMS-X": {
        "url": "sunrise.tm-exchange.com",
        "tags": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
        ],
        "primarytypes": ["Race", "Puzzle", "Platform", "Stunts", "Shortcut", "Laps"],
        "environments": ["", "", "", "", "Island", "Coast", "Bay"],
        "moods": ["Sunrise", "Day", "Sunset", "Night"],
        "inhasrecords": ["No Records", "Has Records"],
        "difficultys": ["Beginner", "Intermediate", "Expert", "Lunatic"],
    },
    "TMN-X": {
        "url": "nations.tm-exchange.com",
        "tags": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
        ],
        "primarytypes": ["Race", "Puzzle", "Platform", "Stunts", "Shortcut", "Laps"],
        "environments": ["", "", "", "", "", "", "", "Stadium"],
        "moods": ["Sunrise", "Day", "Sunset", "Night"],
        "inhasrecords": ["No Records", "Has Records"],
        "difficultys": ["Beginner", "Intermediate", "Expert", "Lunatic"],
    },
}
