sites = {
    "all": {
        "difficulty": ["Beginner", "Intermediate", "Expert", "Lunatic"],
        "inhasrecord": ["No Records", "Has Records"],
        "mood": ["Sunrise", "Day", "Sunset", "Night"],
        "primarytype": ["Race", "Puzzle", "Platform", "Stunts", "Shortcut", "Laps"],
        "unlimiterver": ["Any", "0.4", "0.6", "0.7", "1.1", "1.2", "1.3", "2.0"],
    },
    "TMUF-X": {
        "url": "tmuf.exchange",
        "tag": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
            "Story",
            "Nascar",
            "SpeedFun",
            "Endurance",
            "Altered Nadeo",
            "Transitional",
        ],
        "environment": [
            "",
            "Snow",
            "Desert",
            "Rally",
            "Island",
            "Coast",
            "Bay",
            "Stadium",
        ],
    },
    "TMNF-X": {
        "url": "tmnf.exchange",
        "tag": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
            "Story",
            "Nascar",
            "SpeedFun",
            "Endurance",
            "Altered Nadeo",
            "Transitional",
        ],
        "environment": ["", "", "", "", "", "", "", "Stadium"],
    },
    "TMO-X": {
        "url": "original.tm-exchange.com",
        "tag": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
        ],
        "environment": ["", "Snow", "Desert", "Rally"],
    },
    "TMS-X": {
        "url": "sunrise.tm-exchange.com",
        "tag": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
        ],
        "environment": ["", "", "", "", "Island", "Coast", "Bay"],
    },
    "TMN-X": {
        "url": "nations.tm-exchange.com",
        "tag": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
        ],
        "environment": ["", "", "", "", "", "", "", "Stadium"],
    },
}
