import datetime

today = datetime.datetime.today()

values = {
    "all": {
        "mode": ["Author", "Gold", "Silver", "Bronze", "Finished", "WR"],
        "site": ["TMUF-X", "TMNF-X", "TMO-X", "TMN-X", "TMS-X"],
        "difficulty": ["Beginner", "Intermediate", "Expert", "Lunatic"],
        "inhasrecord": ["No Records", "Has Records"],
        "mood": ["Sunrise", "Day", "Sunset", "Night"],
        "primarytype": ["Race", "Puzzle", "Platform", "Stunts", "Shortcut", "Laps"],
        "unlimiterver": ["Any", "0.4", "0.6", "0.7", "1.1", "1.2", "1.3", "2.0"],
        "inauthortimebeaten": ["Not Beaten", "Beaten"],
        "order1": [
            "",
            "Uploaded (Oldest)",
            "Uploaded (Newest)",
            "Updated (Least recent)",
            "Updated (Most recent)",
            "Awards (Least)",
            "Awards (Most)",
            "Comments (Least)",
            "Comments (Most)",
            "Activity (Least recent)",
            "Activity (Most recent)",
            "Track name (A-Z)",
            "Track name (Z-A)",
            "Author name (A-Z)",
            "Author name (Z-A)",
            "Difficulty (Easiest)",
            "Difficulty (Hardest)",
            "Downloads (Least)",
            "Downloads (Most)",
            "Track value (Least)",
            "Track value (Most)",
            "Awards this week (Least)",
            "Awards this week (Most)",
            "Awards this month (Least)",
            "Awards this month (Most)",
            "Awarded (Least recent)",
            "Awarded (Most recent)",
            "World record set (Least recent)",
            "World record set (Most recent)",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Track Length (Shortest)",
            "Track Length (Longest)",
            "World record time (Shortest)",
            "World record time (Longest)",
        ],
    },
    "TMUF-X": {
        "url": "tmuf.exchange",
        "tag": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
            "Story",
            "Nascar",
            "SpeedFun",
            "Endurance",
            "Altered Nadeo",
            "Transitional",
        ],
        "environment": [
            "",
            "Snow",
            "Desert",
            "Rally",
            "Island",
            "Coast",
            "Bay",
            "Stadium",
        ],
    },
    "TMNF-X": {
        "url": "tmnf.exchange",
        "tag": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
            "Story",
            "Nascar",
            "SpeedFun",
            "Endurance",
            "Altered Nadeo",
            "Transitional",
        ],
        "environment": ["", "", "", "", "", "", "", "Stadium"],
    },
    "TMO-X": {
        "url": "original.tm-exchange.com",
        "tag": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
        ],
        "environment": ["", "Snow", "Desert", "Rally"],
    },
    "TMS-X": {
        "url": "sunrise.tm-exchange.com",
        "tag": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
        ],
        "environment": ["", "", "", "", "Island", "Coast", "Bay"],
    },
    "TMN-X": {
        "url": "nations.tm-exchange.com",
        "tag": [
            "Race",
            "Stunt",
            "Maze",
            "Offroad",
            "Multilap",
            "FullSpeed",
            "LOL",
            "Tech",
            "SpeedTech",
            "RPG",
            "PressForward",
            "Trial",
            "Grass",
        ],
        "environment": ["", "", "", "", "", "", "", "Stadium"],
    },
}

default_data = {
    "version": "2.0.0",
    "exe_path": "",
    "track_dir": "",
    "force_window_size": True,
    "auto_update": False,
    "skip_skipped": True,
    "default_data": True,
    "game_rules": {},
    "track_rules": {},
    "preset": "Default",
    "presets": {
        "Default": {
            "game_rules": {
                "next_mode": "finished",
                "track_limit": {"state": 0, "value": 1},
                "time_limit": {"state": 2, "value": datetime.timedelta(minutes=15)},
                "site": "TMNF-X",
            },
            "track_rules": {
                "uploadedafter": {
                    "state": 0,
                    "value": datetime.datetime(2008, 4, 3, 0, 0, 0),
                },
                "uploadedbefore": {
                    "state": 0,
                    "value": datetime.datetime(
                        today.year, today.month, today.day, 23, 59, 59
                    ),
                },
                "authortimemin": {"state": 0, "value": 0},
                "authortimemax": {"state": 0, "value": 0},
                "inunlimiter": {"state": 0, "value": 0},
                "unlimiterver": {"state": 0, "value": 0},
                "tag": {"state": 0, "value": 0},
                "primarytype": {"state": 0, "value": 0},
                "environment": {"state": 0, "value": 7},
                "mood": {"state": 0, "value": 1},
                "difficulty": {"state": 0, "value": 0},
                "inhasrecord": {"state": 2, "value": 0},
                "inauthortimebeaten": {"state": 0, "value": 0},
                "order1": {"state": 2, "value": 39},
            },
        }
    },
    "banned_tracks": {
        "TMUF-X": set(),
        "TMNF-X": set(),
        "TMO-X": set(),
        "TMS-X": set(),
        "TMN-X": set(),
    },
}
