name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter version number (e.g., v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform_name: linux
            exec_ext: ""
            nuitka_flags: "--enable-plugin=pyqt6"
          - os: windows-latest
            platform_name: windows
            exec_ext: ".exe"
            nuitka_flags: "--enable-plugin=pyqt6 --windows-disable-console --windows-icon-from-ico=assets/icon.ico"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka ordered-set

      - name: Build with Nuitka
        run: |
          python -m nuitka --standalone \
                           --onefile \
                           --remove-output \
                           ${{ matrix.nuitka_flags }} \
                           --output-filename=unplayed \
                           src/main.py

      - name: Prepare Folder and Archive
        shell: bash
        run: |
          mkdir unplayed_folder
          mv unplayed${{ matrix.exec_ext }} unplayed_folder/unplayed${{ matrix.exec_ext }}
          mv unplayed_folder unplayed

          if [[ "${{ matrix.platform_name }}" == "windows" ]]; then
            powershell Compress-Archive -Path unplayed -DestinationPath unplayed-${{ matrix.platform_name }}-${{ github.event.inputs.version }}.zip
          else
            zip -r unplayed-${{ matrix.platform_name }}-${{ github.event.inputs.version }}.zip unplayed/
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: unplayed-${{ matrix.platform_name }}
          path: unplayed-${{ matrix.platform_name }}-${{ github.event.inputs.version }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List files
        run: ls -R

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          files: |
            unplayed-linux-${{ github.event.inputs.version }}.zip
            unplayed-windows-${{ github.event.inputs.version }}.zip
